## U2BCA Application Simulator            ##
##   Copyright (C) 2022 by NAIST UNIV.    ##
##         Primary writer: Pham Hoai Luan ##
##                pham.luan@is.naist.jp   ##

CC=gcc
CFLAGS=-I.


all: test.o
	$(CC) -o main test.o
	./main
	
clean:
	rm -f *.o main		